### ISSUE TITLE
Merge this back?

### ISSUE THREAD

**Issue by thlorenz** [bevry/ansi#1]
Hey @BevryMe, nice work!

Seeing that this is compat with `npm / node` as well I'd love to end up with a package that works anywhere.
I'm willing to give you the related npm packages so people who install `ansi{colors,styles}` get types automagically.

Not sure if this makes any sense, but just wanted to offer.

**Comment by balupton** [comment]
Hey @thlorenz, so I saw this but have been busy. The issue with merging back is you would then have two packages that would do the goal of one. Not sure why they were two packages in the first place. Both your packages have definitely typed packages for them, which I've submitted contributions for. So your package and this package provide types. The reason I made this one is for the deno compat.

So it is up to you on merging back for that advantage. You are welcome to grab the code and push it back, I'm just not sure what the benefit is, hence fork over PR.

Will be maintaining this code going forward. Perhaps linking it as a successor is the way to go, rather than having myself and yourself maintain 3 packages that do the same thing.
